### ISSUE TITLE
Help Desk Form

### ISSUE THREAD

**Issue by Ore3DAccess** [Ore-Design/IT-Helpdesk#243]
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="Generator" content="Microsoft Word 15 (filtered medium)"><style>

</style></head><body lang="EN-US" link="#467886" vlink="#96607D" style="word-wrap:break-word"><div class="WordSection1"><p class="MsoNormal">Mike and Kadyn, </p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal">We’ve learned that the help desk form that is on the BambooHR homepage for employees no longer works. This is also the form that we have attached to onboarding task to notify IT of new hires. </p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal">What should we use instead? </p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal">Amy</p></div></body></html>

**Comment by Kasprenius** [comment]
Made a new one!
