### ISSUE TITLE
Updating Swore Netsuite Search

### ISSUE THREAD

**Issue by Ore3DAccess** [Ore-Design/IT-Helpdesk#253]
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="Generator" content="Microsoft Word 15 (filtered medium)"><style>

</style></head><body lang="EN-US" link="#467886" vlink="#96607D" style="word-wrap:break-word"><div class="WordSection1"><p class="MsoNormal">Mike,</p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal">I have a few more status I need added to the Netsuite search that feed swOre.&nbsp; This should cover everything we need.&nbsp; Let me know if you have any questions.</p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal"><img width="345" height="919" id="Picture_x0020_1" src="cid:image004.png@01DAB8DE.3E19A710" style="width:3.5972in; height:9.5694in"></p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal">The search is: </p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal"><a href="https://3619299.app.netsuite.com/app/common/search/searchresults.nl?searchid=2367&amp;whence=">https://3619299.app.netsuite.com/app/common/search/searchresults.nl?searchid=2367&amp;whence=</a></p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal">&nbsp;</p></div><div style="color:black; font-family:Helvetica"><div><br><img src="https://ore.design/wp-content/uploads/2024/03/20-Email_logo.png" alt="Ore Logo" width="100"> </div><div>Grif Gale <br><div style="color:#FF4C00">Cad Supervisor</div><br><a href="mailto:ggale@ore.design" style="text-decoration:none; color:black">ggale@ore.design</a> <br>→ </div><br><div>1972 W 2425 S<br>Woods Cross, UT 84087</div><br><div><a href="https://ore.design" style="text-decoration:none; color:black">ore.design</a></div><br></div></body></html>

**Comment by Kasprenius** [comment]
Done
