### ISSUE TITLE
Shortcuts in SharePoint

### ISSUE THREAD

**Issue by Ore3DAccess** [Ore-Design/IT-Helpdesk#254]
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="Generator" content="Microsoft Word 15 (filtered medium)"><style>

</style></head><body lang="EN-US" link="#467886" vlink="#96607D" style="word-wrap:break-word"><div class="WordSection1"><p class="MsoNormal">Mike,</p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal">I need a fix so we can use shortcuts in SharePoint.&nbsp;&nbsp;&nbsp; Ultimately what I need to accomplish is to be able to print, for example, &nbsp;the pdf’s for the fire pit, its lid, pan, and glass surround without going to the folders that hold each of those files.&nbsp; Our folder structure is set up so all lids, glass surrounds, pans, etc. are each in their own folders, as well as each firepit in its own.&nbsp; When we were hosting our own file, shortcuts were the solution.&nbsp; I would prefer to keep this same system in SharePoint, but am open to other options as well.</p></div><div style="color:black; font-family:Helvetica"><div><br><img src="https://ore.design/wp-content/uploads/2024/03/20-Email_logo.png" alt="Ore Logo" width="100"> </div><div>Grif Gale <br><div style="color:#FF4C00">Cad Supervisor</div><br><a href="mailto:ggale@ore.design" style="text-decoration:none; color:black">ggale@ore.design</a> <br>→ </div><br><div>1972 W 2425 S<br>Woods Cross, UT 84087</div><br><div><a href="https://ore.design" style="text-decoration:none; color:black">ore.design</a></div><br></div></body></html>

**Comment by Kasprenius** [comment]
Should be able to make them now with editing the location
