### ISSUE TITLE
iPad Request

### ISSUE THREAD

**Issue by Ore3DAccess** [Ore-Design/IT-Helpdesk#255]
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="Generator" content="Microsoft Word 15 (filtered medium)"><style>

</style></head><body lang="EN-US" link="#467886" vlink="#96607D" style="word-wrap:break-word"><div class="WordSection1"><p class="MsoNormal">To whom it may concern,</p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal">I’d like to request an iPad because of its versatility and productivity benefits. The iPad will enhance my ability to showcase the company’s catalog, discuss products, and deliver impromptu presentations during various situations such as lunches, meetings, and while traveling. It will add the convenience of having a portable device that allows me to seize opportunities wherever I am, ultimately improving my efficiency and effectiveness in engaging with clients or colleagues. It will also assist in notetaking during sales meetings. Additionally, it will serve as a great tool during Lunch and Learn presentations, as it will allow me to show products and images not included in the presentation, as well as answering potential questions, on the spot. It’s also useful for tasks during situations where it may not make sense to carry a laptop. In conclusion, it will directly contribute to my productivity and success in my role. </p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal">Thank you,</p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal">Gianni Tarantini</p></div><div style="color:black; font-family:Helvetica"><div><br><img src="https://ore.design/wp-content/uploads/2024/03/20-Email_logo.png" alt="Ore Logo" width="100"> </div><div>Gianni Tarantini <br><div style="color:#FF4C00">Business Developer</div><br><a href="mailto:GTarantini@ore.design" style="text-decoration:none; color:black">GTarantini@ore.design</a> <br>→ 385.295.1090 </div><br><div>1972 W 2425 S<br>Woods Cross, UT 84087</div><br><div><a href="https://ore.design" style="text-decoration:none; color:black">ore.design</a></div><br></div></body></html>

**Comment by Kasprenius** [comment]
Got Ipad
