### ISSUE TITLE
Microsoft Calendar Conflict Messages

### ISSUE THREAD

**Issue by Ore3DAccess** [Ore-Design/IT-Helpdesk#269]
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="Generator" content="Microsoft Word 15 (filtered medium)"><style>

</style></head><body lang="EN-US" link="#0563C1" vlink="#954F72" style="word-wrap:break-word"><div class="WordSection1"><p class="MsoNormal">Hello,</p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal">I am still having issues with my Outlook meeting scheduler. Recently if I create a meeting it gives me an error message saying the following if I try to edit or open the meeting:</p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal"><img width="745" height="91" id="Picture_x0020_1" src="cid:image001.png@01DAC7B6.621E5020" style="width:7.7604in; height:.9479in"></p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal">When I click on the blocked-out portion on my calendar this pops up:</p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal"><img width="1161" height="756" id="Picture_x0020_2" src="cid:image002.png@01DAC7B6.F3426140" style="width:12.0937in; height:7.875in"></p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal">Looking at my calendar, the icon for the meeting has an icon on it that I haven’t seen before.</p><p class="MsoNormal"><img width="207" height="36" id="Picture_x0020_3" src="cid:image003.png@01DAC7B6.F3426140" style="width:2.1562in; height:.375in"></p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal">I have already brought this up to IT before, but I was only given a temporary fix that only fixed one meeting. I cannot edit my meetings, nor can I click on the email that tells me who has accepted the meeting without receiving an error message.</p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal">Let me know what can be done to fix this.</p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal">Thanks,</p></div><div style="color:black; font-family:Helvetica"><div><br><img src="https://ore.design/wp-content/uploads/2024/03/20-Email_logo.png" alt="Ore Logo" width="100"> </div><div>Nicholas Saunders <br><div style="color:#FF4C00">Manufacturing Engineer I</div><br><a href="mailto:nsaunders@ore.design" style="text-decoration:none; color:black">nsaunders@ore.design</a> <br>→ 13853610884 </div><br><div>1972 W 2425 S<br>Woods Cross, UT 84087</div><br><div><a href="https://ore.design" style="text-decoration:none; color:black">ore.design</a></div><br></div></body></html>

**Comment by Kasprenius** [comment]
Updated to new Outlook and fixed problem meeting, hopefully fixes things
