### ISSUE TITLE
Emily Pack

### ISSUE THREAD

**Issue by Ore3DAccess** [Ore-Design/IT-Helpdesk#281]
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="Generator" content="Microsoft Word 15 (filtered medium)"><style>

</style></head><body lang="EN-US" link="#467886" vlink="#96607D" style="word-wrap:break-word"><div class="WordSection1"><p class="MsoNormal">Kadyn, </p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal">Emily Pack is requesting a stand up desk. Could you please get her setup with the one that we found when decluttering?</p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal">Amy</p></div></body></html>

**Comment by Kasprenius** [comment]
Done! :)
