### ISSUE TITLE
*HOT* MRP Google Sheet Throwing Search Errors on Refresh

### ISSUE THREAD

**Issue by Ore3DAccess** [Ore-Design/IT-Helpdesk#288]
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="Generator" content="Microsoft Word 15 (filtered medium)"><style>

</style></head><body lang="EN-US" link="#467886" vlink="#96607D" style="word-wrap:break-word"><div class="WordSection1"><p class="MsoNormal">Our MRP is throwing errors when we try to use the NetSuite Tools refresh.</p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal">These 4 searches are causing issues:</p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal"><img width="588" height="152" id="Picture_x0020_1" src="cid:image001.png@01DAF20F.0A74D0F0" style="width:6.125in; height:1.5833in"></p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal"><a href="https://docs.google.com/spreadsheets/d/1nys1H9q2fq8DlvLj_8SZJ6Kvx4kyQ1RNObAP6z3cUHg/edit?usp=sharing">https://docs.google.com/spreadsheets/d/1nys1H9q2fq8DlvLj_8SZJ6Kvx4kyQ1RNObAP6z3cUHg/edit?usp=sharing</a></p></div><div style="color:black; font-family:Helvetica"><div><br><img src="https://ore.design/wp-content/uploads/2024/08/Offsite_Signature.png" alt="Ore Logo" width="100"> </div><div>Jake Drake <br><div style="color:#FF4C00">Supply Chain Manager</div><br><a href="mailto:jdrake@ore.design" style="text-decoration:none; color:black">jdrake@ore.design</a> <br>→ 8016770356 </div><br><div>1972 W 2425 S<br>Woods Cross, UT 84087</div><br><div><a href="https://ore.design" style="text-decoration:none; color:black">ore.design</a></div><br></div></body></html>

**Comment by Kasprenius** [comment]
Fixed
