### ISSUE TITLE
NetSuite Follow Up Reminders

### ISSUE THREAD

**Issue by Ore3DAccess** [Ore-Design/IT-Helpdesk#300]
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="Generator" content="Microsoft Word 15 (filtered medium)"><style>

</style></head><body lang="EN-US" link="#467886" vlink="#96607D" style="word-wrap:break-word"><div class="WordSection1"><p class="MsoNormal">The follow up reminder’s lists are no longer working after the new switching project status labeling. Also, for the “My Project with Upcoming Follow-Up Dates” please change the search toa rolling 7 days including today.</p></div><div style="color:black; font-family:Helvetica"><div><br><img src="https://ore.design/wp-content/uploads/2024/08/Offsite-Sugnature-Logo-REV.png" alt="Ore Logo" width="100"> </div><div>Matthew Ramsaur <br><div style="color:#FF4C00">Business Developer (West)</div><br><a href="mailto:mramsaur@ore.design" style="text-decoration:none; color:black">mramsaur@ore.design</a> <br>→ 385.295.1085 </div><br><div>1972 W 2425 S<br>Woods Cross, UT 84087</div><br><div><a href="https://ore.design" style="text-decoration:none; color:black">ore.design</a></div><br></div></body></html>

**Comment by mxidis** [comment]
Updated the saved search.
