### ISSUE TITLE
I'm in editing hell 

### ISSUE THREAD

**Issue by Ore3DAccess** [Ore-Design/IT-Helpdesk#309]
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="Generator" content="Microsoft Word 15 (filtered medium)"><style>

</style></head><body lang="EN-US" link="#467886" vlink="#96607D" style="word-wrap:break-word"><div class="WordSection1"><p class="MsoNormal">I’m trying to update the Onboarding 2.0 document and it’s very finnicky and not responsive - there are so many shapes within shapes and when I click around it still won’t let me edit what I want. The formatting is tricky to work with, and in some boxes any misedit can mess up all the text in the same box. </p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal"><img width="278" height="402" id="Picture_x0020_2" src="cid:image001.png@01DB1328.6C41C1F0" alt="A document with text and images

Description automatically generated with medium confidence" style="width:2.8958in; height:4.1875in"></p><p class="MsoNormal">This is what I was working with before and I miss the simplicity of editing <span style="font-family:&quot;Apple Color Emoji&quot;">&#128148;</span> save me IT !!!!</p><p class="MsoNormal"><img width="228" height="159" id="Picture_x0020_3" src="cid:image002.png@01DB1328.E0C83B80" alt="A close up of a cat

Description automatically generated" style="width:2.375in; height:1.6562in"></p></div></body></html>

**Comment by Kasprenius** [comment]
Changed it a little
