### ISSUE TITLE
Cancel Payment link

### ISSUE THREAD

**Issue by Reyzerbit** [Ore-Design/IT-Helpdesk#330]
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="Generator" content="Microsoft Word 15 (filtered medium)"><style>

</style></head><body lang="EN-US" link="#467886" vlink="#96607D" style="word-wrap:break-word"><div class="WordSection1"><p class="MsoNormal"><span style="font-size:12.0pt">&nbsp;</span></p><p class="MsoNormal"><span style="font-size:12.0pt">&nbsp;</span></p><div id="mail-editor-reference-message-container"><div><div><div style="border:none; border-top:solid #B5C4DF 1.0pt; padding:3.0pt 0in 0in 0in"><p class="MsoNormal" style="margin-bottom:12.0pt"><b><span style="font-size:12.0pt; color:black">From: </span></b><span style="font-size:12.0pt; color:black">Natalia Cruz &lt;ncruz@ore.design&gt;<br><b>Date: </b>Thursday, December 5, 2024 at 4:48</span><span style="font-size:12.0pt; font-family:&quot;Arial&quot;,sans-serif; color:black"> </span><span style="font-size:12.0pt; color:black">PM<br><b>To: </b>Brenda@scoteckley.com &lt;Brenda@scoteckley.com&gt;<br><b>Cc: </b>Nate Baldwin &lt;nbaldwin@ore.design&gt;<br><b>Subject: </b>Ore Designs - Payment</span></p></div><div><p class="MsoNormal"><span style="font-size:12.0pt">Hi Brenda, </span></p><p class="MsoNormal"><span style="font-size:12.0pt">&nbsp;</span></p><p class="MsoNormal"><span style="font-size:12.0pt">Please visit the attached link for payment:</span></p><p class="MsoNormal"><span style="font-size:12.0pt">&nbsp;</span></p><p class="MsoNormal"><span style="font-size:12.0pt"><a href="https://webforms.ebizcharge.net/EBizSecureForm.aspx?pid=71d81714-2c2e-4c3b-a9c4-3b4c7edc3fd2" target="fldUrlWindow">https://webforms.ebizcharge.net/EBizSecureForm.aspx?pid=71d81714-2c2e-4c3b-a9c4-3b4c7edc3fd2</a></span></p></div></div></div></div></div></body></html>

**Comment by mxidis** [comment]
This has been removed
