### ISSUE TITLE
NetSuite Search

### ISSUE THREAD

**Issue by Reyzerbit** [Ore-Design/IT-Helpdesk#331]
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="Generator" content="Microsoft Word 15 (filtered medium)"><style>

</style></head><body lang="EN-US" link="#467886" vlink="#96607D" style="word-wrap:break-word"><div class="WordSection1"><p class="MsoNormal">Hi Mike,</p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal">Could you help me put together a list of my top 5 customer with the most projects. </p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal">Thank you so much,</p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal">&nbsp;</p></div><div style="color:black; font-family:Helvetica"><div><br><img src="https://ore.design/wp-content/uploads/2024/03/20-Email_logo.png" alt="Ore Logo" width="100"> </div><div>Gianni Tarantini <br><div style="color:#FF4C00">Business Developer</div><br><a href="mailto:GTarantini@ore.design" style="text-decoration:none; color:black">GTarantini@ore.design</a> <br>→ 385.295.1090 </div><br><div>1972 W 2425 S<br>Woods Cross, UT 84087</div><br><div><a href="https://ore.design" style="text-decoration:none; color:black">ore.design</a></div><br></div></body></html>

**Comment by mxidis** [comment]
https://3619299.app.netsuite.com/app/common/search/searchresults.nl?searchid=2212&saverun=T&whence=
