### ISSUE TITLE
Warranty Email Access

### ISSUE THREAD

**Issue by Reyzerbit** [Ore-Design/IT-Helpdesk#335]
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="Generator" content="Microsoft Word 15 (filtered medium)"><style>

</style></head><body lang="EN-US" link="#467886" vlink="#96607D" style="word-wrap:break-word"><div class="WordSection1"><p class="MsoNormal">Hello Teamsters, </p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal">Can I pretty please with sugar on top get access to this email?</p><p class="MsoNormal">“MX complaints/warranties”</p><p class="MsoNormal">&nbsp;</p><p class="MsoNormal">Sincere salutations, </p><p class="MsoNormal">Wendy </p></div><div style="color:black; font-family:Helvetica"><div><br><img src="https://ore.design/wp-content/uploads/2024/03/20-Email_logo.png" alt="Ore Logo" width="100"> </div><div>Wendy Treloar <br><div style="color:#FF4C00">Operations Assistant</div><br><a href="mailto:WTreloar@ore.design" style="text-decoration:none; color:black">WTreloar@ore.design</a> <br>→ </div><br><div>1972 W 2425 S<br>Woods Cross, UT 84087</div><br><div><a href="https://ore.design" style="text-decoration:none; color:black">ore.design</a></div><br></div></body></html>

**Comment by mxidis** [comment]
Added to warranty email group in O365
